### ISSUE TITLE
Error on Installation Linux Mint

### ISSUE THREAD

**Issue by gr3ym1nd** [sentinel-official/hub#120]
**Describe the bug**
Installation don't can be startet

**To Reproduce**
Only download and try to install

**Expected behavior**
Error Message: Abhängigkeiten nicht erfüllbar: libgconf2-4

**Screenshots**
![grafik](https://user-images.githubusercontent.com/66801099/120232156-432c8f80-c253-11eb-8518-df58e0e42ec2.png)

**Desktop (please complete the following information):**
 - OS: [Linux Mint]
 - Version [Kernel 5.8.0-53]

**Comment by gr3ym1nd** [comment]
libgconf-2-4  (3.2.6-6ubuntu1) is already installed

**Comment by bsrinivas8687** [comment]
Hi @gr3ym1nd 

Please use this version [link](https://github.com/sentinel-official/sentinel/releases/tag/v0.1.4)
