### ISSUE TITLE
Potential overflow/denial of service in provider plan creation

### ISSUE THREAD

**Issue by dimiandre** [sentinel-official/hub#71]
**Describe the bug**
Right now the MsgPlanAdd generates the ID based on the count of plans in the keeper. 
https://github.com/sentinel-official/hub/blob/706826e957c761409060ba17e25ad6854f4c50dd/x/plan/handler.go#L20 

uint64 limit is 18446744073709551615 so still quite hard to reach under standard circumstances, but still possible. 

**To Reproduce**
The max throughput I'm able to reach is 8000 MsgPlanAdd per tx, which will cause an overflow in about 70k years. So not an urgent issue

**Expected behavior**
I suggest to let the client choose the plan-id and change the type from uint64 to string, using uuidv4. I can work on a PR if makes sense

**Additional context**
v0.3.3

**Comment by ironman0x7b2** [comment]
Hi, @dimiandre Thank you for reporting this. We used type uint64 here because it's simple, easy, and takes less space. I feel practically it's not possible for someone to overflow the max value by executing transactions.

**Comment by dimiandre** [comment]
> Hi, @dimiandre Thank you for reporting this. We used type uint64 here because it's simple, easy, and takes less space. I feel practically it's not possible for someone to overflow the max value by executing transactions.

Thanks for the clarification, I agree it's extremely unlikely but if some validators accept 0 fee transactions (like some do in cosmos hub) it's just a matter of time, resources, and how much someone hates the project. But it's also true that with 0 fee txs you can mess up the chain way more than this, so maybe not relevant. 

should I close it?

**Comment by ironman0x7b2** [comment]
Thank you! You can close it.
