### ISSUE TITLE
minimum deposit required for a proposal

### ISSUE THREAD

**Issue by wimel** [sentinel-official/hub#73]
**Describe the bug**
The `mindeposit` on the `gov` module required for a proposal to enter the voting period should be `512tsent`, but with this ammount sent to the proposal, continues in `Deposit Period`. 

**To Reproduce**
Sending the the minimum amount for the deposit period to pass, the proposal remains in the deposit period, you can found the proposal [here](https://explorer.sentinel.co/proposals/1) with the min amount to proposal goes to voting period.

**Expected behavior**
If the minimum amount of `512tsent` is reached, the process should enter the voting period.

**Screenshots**
![prop512](https://user-images.githubusercontent.com/17170149/95065034-cca9b300-0700-11eb-8d9c-737e701c04b1.png)

 - Version:
```sh
name: sentinel-hub
server_name: sentinel-hubd
client_name: sentinel-hub-cli
version: 0.3.3
commit: 706826e957c761409060ba17e25ad6854f4c50dd
build_tags: netgo,ledger
```

**Comment by ironman0x7b2** [comment]
Hi, @wimel Thank you for reporting this.
The deposit value is 1000 TSENT for Turing-3 testnet. You can find the parameters at https://sentinel-test.ping.pub/#/parameter

**Comment by wimel** [comment]
Thanks @ironman0x7b2 !
