### ISSUE TITLE
Lack of seeds

### ISSUE THREAD

**Issue by faddat** [sentinel-official/hub#89]
**Describe the bug**
To join a network, people need seeds or peers, and currently there are none to be found. 

**To Reproduce**
Join the testnet

**Expected behavior**
Seeds should be front and center in readme.md and they should later be baked directly into the binary.

**Comment by bsrinivas8687** [comment]
@faddat Can you please check [here](https://github.com/sentinel-official/docs/tree/master/guides/testnets/turing-3)
